use anyhow::{Context, Result};
use rust_docs_mcp::RustDocsRuntime;
use rust_docs_mcp::cache::CrateCache;
use rust_docs_mcp::cache::features::FeatureOptions;
use rust_docs_mcp::cache::storage::CacheStorage;
use serde_json::{Value, json};
use std::path::Path;

fn write_fixture(root: &Path, name: &str) -> Result<()> {
    std::fs::create_dir_all(root.join("src"))?;
    std::fs::write(
        root.join("Cargo.toml"),
        format!(
            r#"
[package]
name = "{name}"
version = "0.1.0"
edition = "2021"
[features]
default = ["default_symbol"]
default_symbol = []
axum = ["dep:optional_dep"]
actix = []
[dependencies]
optional_dep = {{ package = "optional-package", path = "deps/optional", optional = true }}
"#
        ),
    )?;
    std::fs::write(
        root.join("src/lib.rs"),
        r#"
#[cfg(all(feature = "axum", feature = "actix"))]
compile_error!("axum and actix are mutually exclusive");
#[cfg(feature = "axum")]
pub use optional_dep;
#[cfg(feature = "axum")]
pub fn axum_handler() {}
#[cfg(feature = "actix")]
pub fn actix_handler() {}
#[cfg(feature = "default_symbol")]
pub fn default_handler() {}
"#,
    )?;
    let dep = root.join("deps/optional");
    std::fs::create_dir_all(dep.join("src"))?;
    std::fs::write(
        dep.join("Cargo.toml"),
        "[package]\nname = \"optional-package\"\nversion = \"0.2.0\"\nedition = \"2021\"\n",
    )?;
    std::fs::write(dep.join("src/lib.rs"), "pub fn optional() {}")?;
    Ok(())
}

fn query_params(name: &str, member: Option<&str>, options: Value) -> Value {
    let mut params = json!({"crate_name": name, "version": "0.1.0", "member": member, "pattern": "handler", "limit": 100});
    params
        .as_object_mut()
        .unwrap()
        .extend(options.as_object().unwrap().clone());
    params
}

async fn preview(runtime: &RustDocsRuntime, params: Value) -> Result<Value> {
    let output = runtime
        .search_items_preview(serde_json::from_value(params)?)
        .await;
    let result: Value = serde_json::from_str(&output)?;
    anyhow::ensure!(result["error"].is_null(), "{output}");
    Ok(result)
}

fn names(output: &Value) -> Vec<&str> {
    let mut names: Vec<_> = output["items"]
        .as_array()
        .unwrap()
        .iter()
        .filter_map(|i| i["name"].as_str())
        .collect();
    names.sort();
    names
}

#[tokio::test]
async fn lazy_queries_keep_feature_variants_and_metadata_separate() -> Result<()> {
    let source = tempfile::tempdir()?;
    let cache_dir = tempfile::tempdir()?;
    write_fixture(source.path(), "variant-fixture")?;
    // Download source only. Every documentation variant below is generated by a query.
    let cache = CrateCache::new(Some(cache_dir.path().to_owned()))?;
    cache
        .ensure_crate_source("variant-fixture", "0.1.0", source.path().to_str())
        .await?;
    let runtime = RustDocsRuntime::new(Some(cache_dir.path().to_owned()))?;
    let axum = query_params("variant-fixture", None, json!({"features": ["axum"]}));
    let actix = query_params("variant-fixture", None, json!({"features": ["actix"]}));
    let axum_output = preview(&runtime, axum.clone()).await?;
    assert_eq!(names(&axum_output), ["axum_handler"]);
    let inspected: Value = serde_json::from_str(
        &runtime
            .get_crates_metadata(serde_json::from_value(json!({
                "queries": [{"crate_name": "variant-fixture", "version": "0.1.0"}]
            }))?)
            .await,
    )?;
    assert_eq!(inspected["metadata"][0]["analyzed"], true);
    let listed: Value = serde_json::from_str(&runtime.list_cached_crates().await)?;
    assert_eq!(
        listed["crates"]["variant-fixture"][0]["doc_generated"],
        true
    );
    assert_eq!(
        listed["crates"]["variant-fixture"][0]["variants"]
            .as_array()
            .unwrap()
            .len(),
        1
    );

    let mut import_params = axum.clone();
    import_params["pattern"] = json!("optional_dep");
    let imported = preview(&runtime, import_params.clone()).await?;
    assert_eq!(imported["items"][0]["kind"], "use");
    import_params["item_id"] = json!(
        imported["items"][0]["id"]
            .as_str()
            .unwrap()
            .parse::<i32>()?
    );
    let detail: Value = serde_json::from_str(
        &runtime
            .get_item_details(serde_json::from_value(import_params)?)
            .await,
    )?;
    assert_eq!(detail["reexport"]["source"], "optional_dep", "{detail}");

    assert_eq!(
        names(&preview(&runtime, actix.clone()).await?),
        ["actix_handler"]
    );
    assert_eq!(
        names(&preview(&runtime, axum.clone()).await?),
        ["axum_handler"]
    );

    let defaults = query_params(
        "variant-fixture",
        None,
        json!({"features": ["axum"], "no_default_features": false}),
    );
    assert_eq!(
        names(&preview(&runtime, defaults).await?),
        ["axum_handler", "default_handler"]
    );
    let empty = query_params("variant-fixture", None, json!({"features": []}));
    assert!(names(&preview(&runtime, empty).await?).is_empty());

    let auto = query_params("variant-fixture", None, json!({}));
    assert_eq!(names(&preview(&runtime, auto).await?), ["default_handler"]);
    let storage = CacheStorage::new(Some(cache_dir.path().to_owned()))?;
    let variants = storage.list_variants("variant-fixture", "0.1.0")?;
    assert_eq!(variants.len(), 5);
    let fallback = variants
        .iter()
        .find(|v| v.build.requested == FeatureOptions::Auto)
        .context("Missing auto variant")?;
    assert_eq!(
        fallback.build.effective,
        FeatureOptions::new(None, Some(false), None)?
    );

    // An explicit all-features request must fail without falling back or replacing good docs.
    let all = query_params("variant-fixture", None, json!({"all_features": true}));
    let failed: Value = serde_json::from_str(
        &runtime
            .search_items_preview(serde_json::from_value(all)?)
            .await,
    )?;
    assert!(
        failed["error"]
            .as_str()
            .unwrap()
            .contains("mutually exclusive")
    );
    assert_eq!(storage.list_variants("variant-fixture", "0.1.0")?.len(), 5);

    // The persisted variants survive a fresh runtime as well as an LRU hit.
    drop(runtime);
    let runtime = RustDocsRuntime::new(Some(cache_dir.path().to_owned()))?;
    assert_eq!(
        names(&preview(&runtime, axum.clone()).await?),
        ["axum_handler"]
    );
    for (params, symbol) in [
        (axum.clone(), "axum_handler"),
        (actix.clone(), "actix_handler"),
    ] {
        let mut fuzzy = params.clone();
        fuzzy["query"] = json!(symbol);
        let output: Value = serde_json::from_str(
            &runtime
                .search_items_fuzzy(serde_json::from_value(fuzzy)?)
                .await,
        )?;
        assert_eq!(output["results"][0]["name"], symbol, "{output}");
        let mut deps = params;
        deps["include_tree"] = json!(true);
        let output: Value = serde_json::from_str(
            &runtime
                .get_dependencies(serde_json::from_value(deps)?)
                .await,
        )?;
        let dep = &output["direct_dependencies"][0];
        if symbol == "axum_handler" {
            assert_eq!(dep["resolved_version"], "0.2.0", "{output}");
        } else {
            assert!(dep["resolved_version"].is_null(), "{output}");
        }
    }

    let id = axum_output["items"][0]["id"]
        .as_str()
        .unwrap()
        .parse::<i32>()?;
    let mut details = axum;
    details["item_id"] = json!(id);
    let output: Value = serde_json::from_str(
        &runtime
            .get_item_details(serde_json::from_value(details.clone())?)
            .await,
    )?;
    assert_eq!(output["info"]["name"], "axum_handler");
    let output: Value = serde_json::from_str(
        &runtime
            .get_item_source(serde_json::from_value(details)?)
            .await,
    )?;
    assert!(
        output["code"]
            .as_str()
            .unwrap_or_default()
            .contains("axum_handler"),
        "{output}"
    );
    Ok(())
}

#[tokio::test]
async fn workspace_member_lazy_features_and_dependencies_use_the_member() -> Result<()> {
    let source = tempfile::tempdir()?;
    let cache_dir = tempfile::tempdir()?;
    std::fs::write(
        source.path().join("Cargo.toml"),
        "[workspace]\nmembers = [\"member\"]\nresolver = \"2\"\n",
    )?;
    write_fixture(&source.path().join("member"), "actual-member")?;
    let cache = CrateCache::new(Some(cache_dir.path().to_owned()))?;
    cache
        .ensure_crate_source("workspace-alias", "0.1.0", source.path().to_str())
        .await?;
    let runtime = RustDocsRuntime::new(Some(cache_dir.path().to_owned()))?;
    let params = query_params(
        "workspace-alias",
        Some("member"),
        json!({"features": ["axum"]}),
    );
    assert_eq!(
        names(&preview(&runtime, params.clone()).await?),
        ["axum_handler"]
    );
    let deps: Value = serde_json::from_str(
        &runtime
            .get_dependencies(serde_json::from_value(params)?)
            .await,
    )?;
    assert_eq!(deps["crate_info"]["name"], "actual-member", "{deps}");
    assert_eq!(
        deps["direct_dependencies"][0]["resolved_version"], "0.2.0",
        "{deps}"
    );
    let params = query_params(
        "workspace-alias",
        Some("member"),
        json!({"features": ["actix"]}),
    );
    assert_eq!(names(&preview(&runtime, params).await?), ["actix_handler"]);
    Ok(())
}

#[test]
fn cli_version_and_incompatible_toolchain_diagnostics() -> Result<()> {
    let binary = env!("CARGO_BIN_EXE_rust-docs-mcp");
    let version = std::process::Command::new(binary)
        .arg("--version")
        .env("RUST_DOCS_MCP_TOOLCHAIN", "stable")
        .output()?;
    let stdout = String::from_utf8(version.stdout)?;
    assert!(version.status.success());
    assert!(stdout.contains(rust_docs_mcp::rustdoc::PREFERRED_TOOLCHAIN));
    assert!(stdout.contains("Configured override: stable"));
    let source = tempfile::tempdir()?;
    let cache = tempfile::tempdir()?;
    write_fixture(source.path(), "toolchain-fixture")?;
    let params = json!({"crate_name": "toolchain-fixture", "source_type": "local", "path": source.path(), "features": []});
    let result = std::process::Command::new(binary)
        .env("RUST_DOCS_MCP_TOOLCHAIN", "stable")
        .args([
            "--cache-dir",
            cache.path().to_str().unwrap(),
            "call",
            "cache-crate",
            "--params",
            &params.to_string(),
        ])
        .output()?;
    assert!(!result.status.success());
    let output = String::from_utf8(result.stdout)?;
    assert!(output.contains("Configured toolchain stable"), "{output}");
    assert!(
        output.contains("not compatible") || output.contains("not installed"),
        "{output}"
    );
    Ok(())
}

#[tokio::test]
async fn concurrent_processes_publish_one_complete_variant() -> Result<()> {
    use std::process::{Command, Stdio};
    let source = tempfile::tempdir()?;
    let cache_dir = tempfile::tempdir()?;
    write_fixture(source.path(), "concurrent-fixture")?;
    let cache = CrateCache::new(Some(cache_dir.path().to_owned()))?;
    cache
        .ensure_crate_source("concurrent-fixture", "0.1.0", source.path().to_str())
        .await?;
    let params =
        query_params("concurrent-fixture", None, json!({"features": ["axum"]})).to_string();
    let mut children = Vec::new();
    for _ in 0..2 {
        children.push(
            Command::new(env!("CARGO_BIN_EXE_rust-docs-mcp"))
                .arg("--cache-dir")
                .arg(cache_dir.path())
                .args(["call", "search-items-preview", "--params", &params])
                .stdout(Stdio::piped())
                .stderr(Stdio::piped())
                .spawn()?,
        );
    }
    for child in children {
        let output = child.wait_with_output()?;
        anyhow::ensure!(
            output.status.success(),
            "{} {}",
            String::from_utf8_lossy(&output.stdout),
            String::from_utf8_lossy(&output.stderr)
        );
        assert_eq!(
            names(&serde_json::from_slice(&output.stdout)?),
            ["axum_handler"]
        );
    }
    let storage = CacheStorage::new(Some(cache_dir.path().to_owned()))?;
    assert_eq!(
        storage.list_variants("concurrent-fixture", "0.1.0")?.len(),
        1
    );
    Ok(())
}
